from __future__ import annotations


STATUS_BUCKETS = [
    "Active",
    "Upcoming",
    "Limited",
    "Non-Active",
    "Discontinued",
    "Blanks",
    "N/A",
    "Unknown",
    "Non-ACR",
    "Others",
]


OVERVIEW_FIELD_GROUPS: list[tuple[str, str]] = [
    ("OT Article Number", "Basic product info"),
    ("BRAND", "Basic product info"),
    ("Volume/Unit", "Basic product info"),
    ("Net Weight (g)", "Consumer pack"),
    ("Gross weight (g)", "Consumer pack"),
    ("DEPTH / LENGTH", "Consumer pack"),
    ("HEIGHT", "Consumer pack"),
    ("WIDTH", "Consumer pack"),
    ("Inner box QTY", "Trade pack"),
    ("Inner Gross weight", "Trade pack"),
    ("Inner DEPTH/LENGTH", "Trade pack"),
    ("Inner HEIGHT", "Trade pack"),
    ("Inner WIDTH", "Trade pack"),
    ("Outer box QTY", "Outer box"),
    ("Outer Gross weight", "Outer box"),
    ("Outer DEPTH/LENGTH", "Outer box"),
    ("Outer HEIGHT", "Outer box"),
    ("Outer WIDTH", "Outer box"),
    ("CPNP Number", "Registration"),
    ("UK SCPN NUMBER", "Registration"),
    ("Manufacturer name", "Manufacturer & RP"),
    ("Manufacturer address", "Manufacturer & RP"),
    ("Manufacturer URL", "Manufacturer & RP"),
    ("EU Responsible person", "Manufacturer & RP"),
    ("UK Responsible person", "Manufacturer & RP"),
    ("Ingredient list", "Compliance"),
    ("PAO (Months)", "Compliance"),
    ("Shelf Life (Months)", "Compliance"),
    ("Description (250+ words)", "Compliance"),
    ("Instructions/How to use", "Compliance"),
    ("Warnings", "Compliance"),
    ("Vegan (Y/N)", "Compliance"),
    ("Is EXP date on pack?", "Compliance"),
    ("Is PAO mentioned on Pack?", "Compliance"),
    ("Green claims compliant?", "Compliance"),
    ("Cruelty Free?", "Compliance"),
    ("HEX CODE", "Compliance"),
    ("SUPPLY PRICE", "Product price"),
    ("SUPPLY CURRENCY", "Product price"),
    ("RECOMMENDED RRP", "Product price"),
    ("BAR CODE", "Barcode"),
]


SUMMARY_FIELDS = [
    "BAR CODE",
    "Volume/Unit",
    "Net Weight (g)",
    "Gross weight (g)",
    "DEPTH / LENGTH",
    "HEIGHT",
    "WIDTH",
    "CPNP Number",
    "UK SCPN NUMBER",
    "Manufacturer name",
    "EU Responsible person",
    "UK Responsible person",
    "Ingredient list",
    "PAO (Months)",
    "Shelf Life (Months)",
    "Description (250+ words)",
    "Warnings",
    "Vegan (Y/N)",
    "SUPPLY PRICE",
]


FIELD_ALIASES: dict[str, list[str]] = {
    "OT Article Number": ["OT Article Number", "CODE", "SKU", "Article Number", "Product Code"],
    "BRAND": ["BRAND", "OBJECT", "Brand", "Brand Name"],
    "Volume/Unit": ["Volume/Unit", "UNIT/VOLUME", "Volume", "Unit"],
    "Net Weight (g)": ["Net Weight (g)", "WEIGHT", "Net Weight"],
    "Gross weight (g)": ["Gross weight (g)", "GROSS WEIGHT", "Gross Weight"],
    "DEPTH / LENGTH": ["DEPTH / LENGTH", "DEPTH", "LENGTH", "Depth / Length"],
    "HEIGHT": ["HEIGHT", "Height"],
    "WIDTH": ["WIDTH", "Width"],
    "Inner box QTY": ["Inner box QTY", "INNER BOX QTY"],
    "Inner Gross weight": ["Inner Gross weight", "INNER BOX G.WEIGHT"],
    "Inner DEPTH/LENGTH": ["Inner DEPTH/LENGTH", "INNER BOX LENGTH"],
    "Inner HEIGHT": ["Inner HEIGHT", "INNER BOX HEIGHT"],
    "Inner WIDTH": ["Inner WIDTH", "INNER BOX WIDTH"],
    "Outer box QTY": ["Outer box QTY", "CARTON QTY"],
    "Outer Gross weight": ["Outer Gross weight", "OUTER BOX G.WEIGHT"],
    "Outer DEPTH/LENGTH": ["Outer DEPTH/LENGTH", "OUTER BOX LENGTH"],
    "Outer HEIGHT": ["Outer HEIGHT", "OUTER BOX HEIGHT"],
    "Outer WIDTH": ["Outer WIDTH", "OUTER BOX WIDTH"],
    "CPNP Number": ["CPNP Number", "CPNP NUMBER"],
    "UK SCPN NUMBER": ["UK SCPN NUMBER", "SCPN NUMBER", "UK SCPN"],
    "Manufacturer name": ["Manufacturer name", "MANUFACTURER INFORMATION", "Manufacturer"],
    "Manufacturer address": ["Manufacturer address"],
    "Manufacturer URL": ["Manufacturer URL"],
    "EU Responsible person": ["EU Responsible person", "EU RESPONSIBLE PERSON"],
    "UK Responsible person": ["UK Responsible person", "UK RESPONSIBLE PERSON"],
    "Ingredient list": ["Ingredient list", "INGREDIENTS"],
    "PAO (Months)": ["PAO (Months)", "PAO"],
    "Shelf Life (Months)": ["Shelf Life (Months)", "SHELF LIFE"],
    "Description (250+ words)": ["Description (250+ words)", "DESCRIPTION"],
    "Instructions/How to use": ["Instructions/How to use"],
    "Warnings": ["Warnings", "WARNING"],
    "Vegan (Y/N)": ["Vegan (Y/N)", "VEGAN CERTIFIED?"],
    "Is EXP date on pack?": ["Is EXP date on pack?"],
    "Is PAO mentioned on Pack?": ["Is PAO mentioned on Pack?"],
    "Green claims compliant?": ["Green claims compliant?"],
    "Cruelty Free?": ["Cruelty Free?"],
    "HEX CODE": ["HEX CODE"],
    "SUPPLY PRICE": ["SUPPLY PRICE"],
    "SUPPLY CURRENCY": ["SUPPLY CURRENCY", "SUPPLY PRICE CURRENCY"],
    "RECOMMENDED RRP": ["RECOMMENDED RRP"],
    "BAR CODE": ["BAR CODE", "Barcode", "EAN"],
}

